scylladb/sphinx-scylladb-theme

docs/source/conf.py
docs/source/contribute/upgrade/0-x-to-1-0.rst
docs/source/github-pages.rst

Explains with more detail what it needs to be changed in the Makefile to update to 1.0

Fix upgrade guide

---

sphinx_scylladb_theme/promo-banner.html

Related: [Code Scanning](https://github.com/scylladb/sphinx-scylladb-theme/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmaster)

Fix warning

---

sphinx_scylladb_theme/layout.html

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/409

Improve search element load time with DNS setting

---

docs/_utils/pyproject_template.toml
docs/source/conf.py
docs/source/configuration/index.rst
docs/source/configuration/markdown.md
docs/source/configuration/multiversion.rst
docs/source/configuration/page.rst
docs/source/configuration/redirections.rst
docs/source/configuration/template.rst
docs/source/contribute/contribute-docs.rst
docs/source/contribute/contribute-theme.rst
docs/source/contribute/index.rst
docs/source/deployment/previews.rst
docs/source/examples/code-blocks.rst
docs/source/examples/hero-box.rst
docs/source/examples/index.rst
docs/source/examples/panel-box.rst
docs/source/examples/text.rst
docs/source/examples/topic-box.rst
docs/source/getting-started/index.rst
docs/source/getting-started/toolchain.rst
docs/source/index.rst
docs/source/upgrade/1-1-to-1-2.rst
docs/source/upgrade/CHANGELOG.md
docs/source/upgrade/index.rst
poetry.lock
pyproject.toml

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/391 and part of https://github.com/scylladb/sphinx-scylladb-theme/issues/395
-  Update CHANGELOG
- Write migration guide with breaking changes
- Update docs
- Bump version number

Release 1.2

---

docs/source/conf.py
sphinx_scylladb_theme/header.html

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/419

Fix alternator link

---

docs/source/upgrade/CHANGELOG.md

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/424

Fix Link Checker Report

---

sphinx_scylladb_theme/custom-scripts.html

we are not using marketo anymore

remove marketo

---

docs/source/contribute/contribute-docs.rst

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/443

Fix broken link

---

docs/source/conf.py
docs/source/configuration/redirects.rst
docs/source/contribute/contribute-docs.rst
docs/source/deployment/previews.rst
docs/source/examples/index.rst
docs/source/getting-started/index.rst
docs/source/getting-started/installation.rst
docs/source/getting-started/quickstart.rst
docs/source/index.rst
docs/source/upgrade/1-2-to-1-3.rst
docs/source/upgrade/CHANGELOG.md
poetry.lock
pyproject.toml
sphinx_scylladb_theme/contribute.html
sphinx_scylladb_theme/versions.html

Related issue https://github.com/scylladb/sphinx-scylladb-theme/issues/548

Release 1.3.0

---

sphinx_scylladb_theme/custom-scripts.html

Adds Zendesk verification tag.
1. Clone this PR and enter the docs folder.
2. Run `make preview`.
3. Open http://127.0.0.1:5500
4. Right-click any part of the page and choose **Inspect**.
5. Verify the meta tag exists under html > head selector:

Add zendesk verification tag

---

docs/source/configuration/multiversion.rst
docs/source/upgrade/CHANGELOG.md
poetry.lock
pyproject.toml

Update CHANGELOG and version number before releasing 1.3.2

Update theme 1.3.2

---

sphinx_scylladb_theme/utils.py
tests/test_utils.py

Reverts scylladb/sphinx-scylladb-theme#610 
We will release this change in a future theme realease as a breaking change

Revert "Fix multiversion selector exact string"

---

poetry.lock
pyproject.toml
sphinx_scylladb_theme/contribute.html

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/642
1. Clone the PR.
2. Go to the docs folder.
2. Run ``make preview``
3. Open http://127.0.0.1:5500/getting-started/
4. Click on the "Edit this page" button
5. The URL should be "github.com/scylladb/sphinx-scylladb-theme/edit/**master**/docs/source/getting-started/index.rst"

Update "Edit this page" opens default branch

---

sphinx_scylladb_theme/header.html

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/648
1. Clone the PR. 
2. Go to the docs folder.
2. Run ``make preview``.
3. Open http://localhost:5500/
4. See the new header:

Remove Cloud app from header

---

sphinx_scylladb_theme/breadcrumbs.html

Closes https://github.com/scylladb/scylladb/issues/13117#issuecomment-1463614351

Fix breadcrumb links

---

sphinx_scylladb_theme/header.html

update link to the open source project. 

---

extensions/sphinx-multiversion/README.md
extensions/sphinx-multiversion/setup.py
extensions/sphinx-multiversion/sphinx_multiversion/__init__.py
extensions/sphinx-multiversion/sphinx_multiversion/git.py

Attempt to fix https://github.com/scylladb/scylla-enterprise/issues/3414
I already deployed the new version of the sphinx-multiversion extension. It will work fine if the next build of the `scylla-enterprise` repo publishes the docs for the `enterprise` branch.

feat: skip lfs smudge

---

sphinx_scylladb_theme/contribute.html
sphinx_scylladb_theme/feedback.html

Should be
"I would like to report an issue **on** page"
not
"I would like to report an issue **in** page"

Fix typo in issue url

---

.github/workflows/docs-pages.yaml

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/886
Tests https://github.com/scylladb/scylladb/pull/17281 proposed solution in this repo.

Trigger publication when backporting

---

.github/workflows/docs-pages.yaml
docs/source/upgrade/1-6-to-1-7.rst
docs/source/upgrade/CHANGELOG.md
docs/source/upgrade/index.rst
poetry.lock
pyproject.toml

Docs + update files to preprare the 1.7 release

Release 1.7

---

docs/source/conf.py
docs/source/upgrade/1-6-to-1-7.rst
docs/source/upgrade/_partials/docs-pages-1.7.yml

List branch-1.7 in conf.py and fixes indentation in a code example

List 1.7 in conf.py

---

sphinx_scylladb_theme/scylladb-scripts.html

Changes GTM scripts order as requested via email.
Build the docs locally & check the site in the browser.  Make sure it renders without errors.

chore: change scripts order

---

docs/source/conf.py

Publish 1.8 docs and make them the default branch.

Publish 1.8 docs

---

docs/source/upgrade/CHANGELOG.md
pyproject.toml

Adds changelog for 1.8.2 and bumps the theme version before releasing.

Release 1.8.2

---

sphinx_scylladb_theme/alert.html
sphinx_scylladb_theme/layout.html

Closes #1328
Preview:
Alert in https://sphinx-theme.scylladb.com/master/getting-started/ should render as expected once we merge this PR.

fix: alerts position

---

sphinx_scylladb_theme/header.html

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/1438

Update header links

---

sphinx_scylladb_theme/header.html

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/1460

Replace download link
