docs/source/conf.py
docs/source/index.rst

Now that the theme is open-source, we can enable the "Edit on GitHub" option.
1. Clone this PR. For more information, see [Cloning pull requests locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).
2. Enter the docs folder, and run:
```
make preview
````
3. Open http://127.0.0.1:5500/ with your favorite browser, and navigate to an internal page. The Contribute button should have the new option "Edit on GitHub".

Add Edit on GitHub button

---

sphinx_scylladb_theme/layout.html

Closes #252 #202 
Updates the warning message to:
>You are not reading the latest stable version of this documentation. If you want up-to-date information, please have a look at X.X.
1. Clone this PR. For more information, see [Cloning pull requests locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).
2. Enter the docs folder, and run:
```
make multiversionpreview
````
3. Open ``http://127.0.0.1:5500/master`` with your favorite browser. 
4. Enter an internal documentation page, the warning should look like:

Update warning message

---

docs/Makefile
docs/source/conf.py
poetry.lock
pyproject.toml

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/235
Updates the extensions Sphinx and recommonmark to the latest version.
1. Clone this PR. For more information, see [Cloning pull requests locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).
2. Enter the docs folder, and run:
```
make preview
````
3. Open http://127.0.0.1:5500/ with your favorite browser. The site should look the same and the build must complete without errors.

Update Sphinx to latest version

---

docs/source/examples/code-blocks.rst
docs/source/github-pages.rst
docs/source/upgrade/CHANGELOG.md
poetry.lock
pyproject.toml
sphinx_scylladb_theme/__init__.py
sphinx_scylladb_theme/lexers/__init__.py

Fixes an error ``TypeError: 'CQLLexer' object is not callable`` I got when installing the new version of the theme in the project scylla-docs.
From [3.x](https://www.sphinx-doc.org/en/master/changes.html#release-2-1-0-released-jun-02-2019), the function ``add_lexer()`` now takes a Lexer class instead of instance.
Additionally, this PR adds some missing updates in the CHANGELOG.

Release 1.1.1

---

.github/workflows/docs-links.yaml
.lycheeignore
docs/source/deployment/production.rst
docs/source/examples/links.rst
docs/source/upgrade/CHANGELOG.md

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/234
Adds [lychee](https://github.com/lycheeverse/lychee), a link checker that finds broken URLs in MarkDown and RestructuredText files.
Once a week, a GitHub Action runs lychee to find for broken links in *.md and *.rst files.
If there are broken links, the action will create a new issue in the same repository with the links that have to be fixed.
It is possible to exclude some links from the analysis by listing them in the file ``.lycheeignore``.

Add link checker on CI

---

sphinx_scylladb_theme/layout.html

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/405
Adds dynamically the correct canonical URL:
* If multiversion is set, the canonical URL has the form: `<link rel="canonical" href="{{ html_baseurl }}/{{latest_slug}}/{{ pagename }}.html"/>`
* Otherwise: `<link rel="canonical" href="{{ html_baseurl }}/{{ pagename }}.html"/>`

Fix canonical tag

---

sphinx_scylladb_theme/layout.html

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/405
Removes `/index.html` in projects that do not use the multi version plugin (e.g scylla-docs), which is causing duplicate content errors.
1. Clone this PR.
2. Run ``make preview`` to run the docs without the multiversion plugin.
3. Inspect the code. The canonical tag does not have the "index.html" suffix:

Fix canonical url if multiversion is not used

---

sphinx_scylladb_theme/contribute.html

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/525
1. Build the docs with ``make preview`` and open the preview in your browser.
2. Click on "Create an issue" button.
3. The issue title should have the prefix "Docs:".
4. The issue should have the label "documentation".

Add "docs" prefix and "documentation" label to issues created with "Create an issue"

---

sphinx_scylladb_theme/versions.html

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/545
1. Clone this PR.
2. Edit the `BRANCHES` arrray in https://github.com/scylladb/sphinx-scylladb-theme/blob/master/docs/source/conf.py#L15 as follows to leave one version:
> BRANCHES = ["branch-1.2"]
3. Run `make multiversionpreview` and open http://localhost:5500. You should see the multiversion dropdown with one version.

Show one version in dropdown

---

sphinx_scylladb_theme/utils.py
tests/test_utils.py

Fix for https://github.com/scylladb/scylla-manager/issues/3261
Updates the `multiversion_regex_builder` utility to only match exact strings.
Before:
Now:
1. Create a new branch "1.3-patch".
``git checkout -b 1.3-patch``
2. Check out this pull request.
3. Build the docs with ``make multiversionpreview``.
You should not see "1.3-patch"  in the multiversion dropdown selector, but "1.3" should still appear:

Fix multiversion selector exact string

---

sphinx_scylladb_theme/utils.py
tests/test_utils.py

Fix for https://github.com/scylladb/scylla-manager/issues/3261
Updates the `multiversion_regex_builder` utility to only match exact strings.
Before:
Now:
1. Create a new branch "1.3-patch".
```
git checkout -b 1.3-patch
```
2. Check out this pull request.
3. Build the docs with ``make multiversionpreview``.
You should not see "1.3-patch"  in the multiversion dropdown selector, but "1.3" should still appear:

Adds back "Revert "Fix multiversion selector exact string""

---

sphinx_scylladb_theme/__init__.py
sphinx_scylladb_theme/extensions/validations.py
tests/extensions/test_validations.py

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/210
1. Clone this PR.
2. Rename a file within the `docs` folder and add an underscore (e.g. `docs/source/configuration/markdown.md `-> `docs/source/configuration/markdown_test.md`).
3. In the `docs` folder, run ``make preview``.
4. You should see the `Warning: Document name contains underscores: configuartion/markdown_test`.

Raise warning if doc has underscores

---

docs/source/conf.py
docs/source/configuration/template.rst
sphinx_scylladb_theme/extensions/validations.py
sphinx_scylladb_theme/theme.conf
tests/extensions/test_validations.py

Option required to update Java and CPP drivers to 1.4.x.
Note that it is not possible to rename some files on these repos since the docs are being synched from an upstream repo.
The new option is tested in https://github.com/scylladb/sphinx-scylladb-theme/actions/runs/4577000903/jobs/8081874608?pr=741

docs: Add option to skip theme warnings

---

docs/source/conf.py

The links in the current `sitemap.xml` file are broken:
Let's use this pull request and repo to test if prepending the backslash generates the correct sitemap URLs.
With the next theme breaking update, we'll backport this change to other projects. See #774

Fix sitemap.xml

---

docs/source/conf.py
docs/source/getting-started/quickstart.rst

- List 1.6 docs in the multiversion selector
- Update dependencies in the quickstart guide.

docs: enable 1.6 docs

---

docs/source/upgrade/CHANGELOG.md
pyproject.toml

Fixes https://github.com/scylladb/sphinx-scylladb-theme/issues/966
Adds import lib-metadata as a required dependency.
Docs should build without errors and [rust build](https://github.com/scylladb/sphinx-scylladb-theme/issues/966) must pass.

fix importlib dependency (2nd attempt)

---

extensions/sphinx-scylladb-markdown/setup.py
extensions/sphinx-scylladb-markdown/sphinx_scylladb_markdown/__init__.py

For compatibility and to prevent warnings when transitioning from the existing scylla-operator extension, this PR sets `app.config.myst_heading_anchors = 6`. 
This configuration aligns with the default values used in the Scylla Operator extension (see https://github.com/scylladb/scylla-operator/blob/master/docs/source/_ext/scylladb_markdown.py#L25)

Add myst_heading_anchors option

---

docs/source/examples/panel-box.rst
docs/source/examples/topic-box.rst
sphinx_scylladb_theme/extensions/topic_box.py

Adds the option to open topic boxes in the same tabs, even if the link is external.
1. Build the docs.
2. Open http://127.0.0.1:5500/examples/topic-box/#topic-with-external-link-same-tab
3. The exterrnal link should open on the same tab since it has the `:link_target: _self` set.

Add option to open topic-box in same tab

---

docs/source/configuration/page.rst
sphinx_scylladb_theme/__init__.py
sphinx_scylladb_theme/layout.html

Adds the option to not load the ``doctools.js`` script injected automatically by Sphinx.
We need this option to make the theme compatible with Swagger UI compatible with the 1.2 spec.
1. Add the `:exclude-doctools:` at the top of any RST page.
2. Build the docs.
3. Open the page edited in the browser.
3. Inspect the code and search for "doctools.js". You should not see any results.
4. Go to a different page and search for "doctools.js". You should get one result.

Add exclude-doctools option

---

.github/workflows/docs-pages.yaml
.github/workflows/docs-pr.yaml
docs/source/upgrade/1-6-to-1-7.rst
docs/source/upgrade/CHANGELOG.md

The [Docs / Publish](https://github.com/scylladb/sphinx-scylladb-theme/actions/runs/8658481683/job/23746809898) actions fails.
This is because GitHub is parsing 3.10 as a number as 3.1 rather than a string "3.10".
We we'll check it works as expected after merging the PR.

fix: workflow python version

---

extensions/sphinx-multiversion/README.md
extensions/sphinx-multiversion/setup.py
extensions/sphinx-multiversion/sphinx_multiversion/main.py
extensions/sphinx-multiversion/sphinx_multiversion/sphinx.py

Closes https://github.com/scylladb/sphinx-scylladb-theme/issues/1006
It's challenging to test the changes in this PR, but I can write a guide if necessary or go through the steps in a call.
I've tested the changes against the enterprise repo.
After merging, I'll release a new version of the multiversion extension, making it possible to define `exclude_patterns` per version.

feat: define exclude_pattern per version

---

docs/source/examples/links.rst

This PR adds an entry to the "Links" table with a description of how to create links to parameters on the automatically generated Configuration Parameters page.

doc: document creating links to configuration parameters

---

docs/Makefile
docs/_utils/pyproject_template.toml
docs/source/commands.rst
docs/source/getting-started/quickstart.rst
docs/source/upgrade/1-7-to-1-8.rst

Related issue https://github.com/scylladb/sphinx-scylladb-theme/issues/849#issuecomment-2381991595
Separates the update command from the setup command in the docs Makefile.
This separation is necessary because, starting with Sphinx ScyllaDB Theme version 1.8, the versions are no longer strictly pinned in the `pyproject.toml` file. This change ensures that the versions defined in the `poetry.lock` file (committed to the repository) are used for production builds.
1. Build the docs locally using `make preview`.
2. Verify that the dependencies in the `poetry.lock` file remain unchanged.

fix: add update command

---

docs/source/examples/glossary.rst
docs/source/examples/tooltips.rst
sphinx_scylladb_theme/extensions/include_tooltip.py
tests/extensions/test_include_tooltip.py

Related issue #873 
While integrating tooltips into the open-source project, I encountered an issue where the glossary entries were not loading consistently. This was due to their dependency on where the glossary entries were defined and whether Sphinx processed them before or after rendering the tooltips.
This pull request addresses the issue by adding placeholders for all tooltips. Once the glossary entries have been loaded, the placeholders are replaced with the correct values.
Additionally, I have included examples showing how longer tooltips with special characters are rendered.
1. Build the documentation.
2. Go to the **Examples > Tooltips** page.
3. Verify that the examples render as expected.

fix: tooltip glossary priority

---

docs/source/commands.rst
docs/source/getting-started/installation.rst
docs/source/getting-started/quickstart.rst

Related PR https://github.com/scylladb/sphinx-scylladb-theme/pull/1259
Adds a troubleshooting note for users experiencing issues with keyring and Poetry.

docs: add keyring troubleshooting

---

sphinx_scylladb_theme/utils.py
tests/test_utils.py

Related issue: https://github.com/scylladb/scylladb-docs-homepage/pull/30
Adds a helper to get multiversion data from a remote URL.
To test the changes, we'll build multiple versions using data from the following URL:  
https://gist.github.com/dgarcia360/d18edbfac5e2fc1443ba0819840e2fd1  
```json
{
"tags": [],
"branches": ["master", "branch-1.8"],
"latest": "branch-1.8",
"unstable": ["master"],
"deprecated": []
}
```
1. Checkout master and branch-1.8 branches:
```bash
git checkout branch-1.8
git checkout master
```
2. Checkout this PR:
```bash
gh pr checkout 1303
```
3. Edit `docs/conf.py`global variables section as follows:
```python
VERSIONS_URL = "https://gist.githubusercontent.com/dgarcia360/d18edbfac5e2fc1443ba0819840e2fd1/raw/dcf460800849f5bc623982532edeb70499f0e3a9/gistfile1.json" …
```

feat: add fetch_multiversion_configuration

---

docs/source/configuration/template.rst
sphinx_scylladb_theme/extensions/multiversion.py
sphinx_scylladb_theme/theme.conf

Adds an option to override the multiversion redirect for the main domain.
It is particularly useful for redirecting `docs.scylladb.com/manual` to `docs.scylladb.com/manual/stable` instead of `docs.scylladb.com/stable`.
1. Open `docs/conf.py`.
2. Define a custom redirect in `html_theme_options` as follows:
```python
html_theme_options = {
"redirect": "/manual/stable",
}
```
3. Build the documentation using `make multiversionpreview`.
4. Verify that `http://localhost:5500/` redirects to `/manual/stable` instead of `/stable`.

feat: override multiversion redirect

---

docs/source/configuration/multiversion.rst
docs/source/upgrade/CHANGELOG.md
pyproject.toml

Updates changelog and version number before releasing 1.8.4

chore: release 1.8.4

---

sphinx_scylladb_theme/alert.html
sphinx_scylladb_theme/layout.html

Removes the "We’re updating our license & versioning policy" banner from internal pages.
This is challenging to test since it wasn’t showing in this repo either.  You can verify that the banner appears on the landing page but not on internal pages after running `make preview`.

rm: license alert

---

docs/source/index.rst

Removes the alert on the theme docs landing (we added it for testing purposes):

Remove alert from homepage (docs theme)

---

extensions/sphinx-multiversion/README.md
extensions/sphinx-multiversion/setup.py
extensions/sphinx-multiversion/sphinx_multiversion/__init__.py
extensions/sphinx-multiversion/sphinx_multiversion/main.py
extensions/sphinx-multiversion/sphinx_multiversion/sphinx.py

Allow defining `myst_substitutions` per branch or version instead of falling back to the default branch values.
This follows a similar approach to the `rst_prolog` variable, but applied to Myst.
Tested locally, though it’s tricky to reproduce. The steps are:
1. Replace the PyPI extension with the local extension.
2. Define myst_substitutions variable with different values in multiple branches.
3. Run multiversion.
After merging, I will release a new version of the extension.

feat: define myst_substitutions per version
